### ISSUE TITLE
Connection timeout for Kafka/Zookeeper

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#211]
We had the security group for MKS not correctly configured and therefore the pod would just hang. Ideally, there should be a feedback loop to inform the user that the connection wasn't possible within a specified time.

**Comment by SaaldjorMike** [comment]
Right now we don't have the best feedback loop regarding misconfigurations. The only thing we have right now is that the HumioCluster will enter state `ConfigError` if we can see the configuration is broken from the perspective of the operator. The problem is here that the operator might not be aware of the fact that the configuration is invalid due to things like misconfigured security groups and such.

I'm guessing it wouldn't be ideal to just enter `ConfigError` by default if we are unable to bootstrap Humio nodes after a fairly long timeout?

Generally I think Humio itself should do a better job of logging out that the problem is related to not being able to reach ZK/Kafka.

**Comment by estahn** [comment]
Yes, as discussed via Slack, it would make more sense to have this in Humio instead of the operator. Will close this.
