### ISSUE TITLE
Ability to disable es ingress

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#212]
We don't have the need for an external ingress, it's all internal. Would be great to have an option to remove this additional ingress.

**Comment by SaaldjorMike** [comment]
I think the simplest solution here would be to do something like this:

Split up ingress object creation and instead of assuming both `hostname` and `esHostname`, then check for the content of the fields and only create the ingress objects that are relevant for each of those hostnames.

In that case, you could just leave out `esHostname` if you do not want the additional hostname/ingress. 

Would that work for you?

**Comment by estahn** [comment]
Yes, it's a minor issue and it's mainly to reduce the possible attack surface.
