### ISSUE TITLE
Service Topology Support

### ISSUE THREAD

**Issue by estahn** [humio/humio-operator#340]
**Is your feature request related to a problem? Please describe.**

Our traffic cost if fairly high due to Interzone traffic. [Service Topology](https://kubernetes.io/docs/concepts/services-networking/service-topology/) solves this issue.

**Describe the solution you'd like**

Ability to annotate the service with service topology definition.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jswoods** [comment]
It looks like service topology is deprecated in favor of https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints. As far as I can tell from the docs, this can be enabled with:
```
spec:
  humioServiceAccountAnnotations:
    service.kubernetes.io/topology-aware-hints: auto
```

I have not personally tried this but I think this is something we'd like to test.  As far as Service Topology, I don't believe we'll want to add support for that since it's deprecated.
