### ISSUE TITLE
humioDataPath different from what humio expects

### ISSUE THREAD

**Issue by mahlunar** [humio/humio-operator#478]
Earlier, when deploying humio to k8s our selves, we mounted `humio-data` to `/data`

Now, we have switched to using the operator with, S3 enabled, which have been working for several months with the following volume config:

```
  dataVolumeSource:
    emptyDir: {}
```

We want to follow best practices before going live with the operator, so we are trying out NVMe instances on AWS using the following config:

```
  dataVolumeSource:
      hostPath:
        path: "/mnt/localssd/humio"
        type: "DirectoryOrCreate"
```

We have also set the `podSecurityContext` to make sure that the user has the correct permissions.

```
podSecurityContext:
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
```
We then get the following error when starting a pod:

```
mkdir: cannot create directory '/data/logs': Read-only file system
ERROR StatusLogger Reconfiguration failed: No configuration found for 'AsyncContext@c387f44' at 'null' in 'null'
Humio data dir must be writable. Tried to write to dir=/app/humio/humio-data
06:26:23.927 [main] ERROR com.humio.core.Context$ - Humio data dir must be writable. Tried to write to dir=/app/humio/humio-data
06:26:23.927 [main] ERROR com.humio.main.ServerRunner$ - Got exception starting pid=1
com.humio.exceptions.HumioException: Humio data dir must be writable. Tried to write to dir=/app/humio/humio-data
	at com.humio.exceptions.HumioException$.apply(HumioException.scala:29) ~[humio-assembly.jar:0.1]
	at com.humio.core.Context$.verifyWritableDirectories(Context.scala:203) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner$.main(ServerRunner.scala:103) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]
```

It looks like we have no control over the `/data` path which is required by the humio pod to write logs in `/data/logs` but it seems like the operator is defaulting to `/data/humio-data` here https://github.com/humio/humio-operator/blob/b5153c9672c04bc2efa66884f027dde075faba43/controllers/humiocluster_pods.go#L50

**Comment by SaaldjorMike** [comment]
Could you please check what the permissions are if you check `/mnt/localssd/humio` on the host itself? 

In general you should be able to use e.g. "user-data" which gets executed on EC2 instance startup, which could then mount the ephemeral NVMe disk on `/mnt/localssd/humio`. If there's multiple NVMe disks, you can also RAID the disks together with RAID-0 and mount that to `/mnt/localssd/humio` for even better performance. After it is mounted, you can e.g. run `chown` on the mountpoint to make sure uid 65534 has access to write files inside `/mnt/localssd/humio`, also something you could do inside something like "user-data".

---

`mkdir: cannot create directory '/data/logs': Read-only file system` <- that entry is safe to ignore, since that's just the `humio/humio-core` container trying to create a directory which we won't be using here since the container outputs are sent to stdout and stderr of the container. Just in case you were wondering if this is a problem as well. I can see however that it might be a little misleading and is likely why you are thinking the mountpoint should be `/data` and not `/data/humio-data`.

**Comment by mahlunar** [comment]
Thanks for the suggestion.

We ended up running the following script on EC2 instance startup which did the trick:

```sh
mkdir /mnt/localssd/humio && chown 65534 /mnt/localssd/humio
```
