### ISSUE TITLE
Supply empty-dir for java logs

### ISSUE THREAD

**Issue by ryanfaircloth** [humio/humio-operator#610]
The current container will attempt to write java runtime logs (GC, JIT) etc to disk (to be picked up by sidecar) however the container spec does not provide a mount. To resolve this issue add an empty-dir mount to /data/java-logs, Set the value of "JVM_LOG_DIR" env var to "/data/java-logs" by default if not provided by CRD

**Comment by SaaldjorMike** [comment]
The operator already defaults to configure Humio to send all logs to stdout/stderr - including GC logs and such. It does this by pointing Humio to a "throw json to stdout/stderr" configuration file for log4j.

It's true that the container itself assumes those things if you'd spin them up manually using some container runtime, but that's why the operator implementation overrides that default container behavior and changes it to configure the target to be stdout/stderr.

Maybe I'm misunderstanding something.

**Comment by ryanfaircloth** [comment]
The override doesn’t cover gc logs causing an error at startup

**Comment by SaaldjorMike** [comment]
GC logs are shipped to stdout by default. What "error at startup" are you referring to? Do you have a snippet/example you can share?
