### ISSUE TITLE
Raising GitHub Issue: Tracking CVEs for humio/humio-operator:0.10.1 Release

### ISSUE THREAD

**Issue by Manikanth06** [humio/humio-operator#715]
We are currently employing humio-operator version 0.10.1, which has been identified as containing several CVEs requiring resolution. Our environment is built on Kubernetes version 1.18, and due to various constraints, an immediate upgrade to a higher Kubernetes version is not feasible. It's worth noting that any humio-operator version beyond 0.10.1 mandates at least Kubernetes 1.19, which aligns with our current limitations.

Hence, we earnestly request your assistance in addressing the CVEs detected through the trivy scan within humio-operator version 0.10.1. This approach would greatly aid us in maintaining security without necessitating a Kubernetes version upgrade at this point. Your support in rectifying these vulnerabilities would be highly appreciated.

**Comment by jacobmovingfwd** [comment]
As per our [Statement of Support](https://library.humio.com/release-notes/notices-statement-of-support.html#notices-statement-of-support-version-support), we can only support prior versions for 1 year after they are released. Version 0.10.1 was released in July 2021.
Additionally, we generally do not backport updates. 
I'm sorry, but the only route forward is to update your Humio Operator.

**Comment by jswoods** [comment]
Hi @Manikanth06. As @jacobmovingfwd mentioned, we do not generally backport updates for old versions. I have however pushed the image `humio/humio-operator:0.10.1.patch.2023-08-23.1` based on a branch here https://github.com/humio/humio-operator/tree/0.10.1.patch.2023-08-23 which contains updates to go and system packages that will address the CVEs.

Since we do not have a backport strategy for this type of work, please consider this a one time patch.

To use this image, update the humio-operator values.yaml file for the operator helm chart like so:
```yaml
operator:
  image:
    repository: humio/humio-operator
    tag: 0.10.1.patch.2023-08-23.1
  ```

**Comment by Manikanth505** [comment]
Hi @jswoods. Is this patch compatible with the kubernetes-1.18 version, could you clarify this as this is crucial?
